[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.0.0"
edition = "2024"
license = "MIT"
homepage = "https://jeffnyman.github.io/rezrov"
repository = "https://github.com/jeffnyman/rezrov"
readme = "README.md"

[workspace.dependencies]
rezrov-zterp = { path = "crates/zterp", version = "0.0.0" }
rezrov-gterp = { path = "crates/gterp", version = "0.0.0" }
rezrov-cli-shell = { path = "crates/cli-shell", version = "0.0.0" }
